#!/usr/bin/env python3
"""Fixture helpers shared by the runner tests: a throwaway limber-shaped git repo, the stub
build environment injection, a shrunken TUNE-1 schedule for fast end-to-end runs and the
no-bytecode guard."""
import json
import os
import shutil
import subprocess
import sys

from scripts import apply_poseidon_tuning as apply_tuning
from scripts import poseidon_common as pc
from scripts import poseidon_runner as runner
from scripts.tests import stub_build_env as sbe

HERE = os.path.dirname(os.path.abspath(__file__))
REAL_REPO = os.path.dirname(os.path.dirname(HERE))
FIXTURES = os.path.join(HERE, "fixtures")
CRIT_SAMPLE = os.path.join(FIXTURES, "crit-sample")
STUB_LIMBER_RUNNER = os.path.join(HERE, "stub_limber_runner.py")

CARGO_TOML = """[package]
name = "limber"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "=0.7.0", default-features = false, features = ["cargo_bench_support"] }
rand_chacha = "=0.3.1"

[[bench]]
name = "poseidon_modp"
harness = false
test = false

[profile.bench]
opt-level = 3
debug = false
strip = "none"
debug-assertions = false
overflow-checks = false
lto = "fat"
codegen-units = 1
incremental = false
"""
CARGO_LOCK = """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "criterion"
version = "0.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e1c047a62b0cc3e145fa84415a3191f628e980b194c2755aa12300a4e6cbd928"

[[package]]
name = "limber"
version = "0.1.0"
dependencies = [
 "criterion",
 "rand_chacha",
]

[[package]]
name = "rand_chacha"
version = "0.3.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e6c10a63a0fa32252be49d21e7709d4d4baf8d231c2dbce1eaa8141b9b127d88"
"""
GENERATED_MODULE = apply_tuning.MODULE_PATH
SECURITY_FIXTURE = {"schema": "limber/security-accounting/v1", "variants": {"hyrax": {},
                                                                              "brakedown": {}},
                    "events": []}
# H = 10 combined-circuit dimensions the stub metadata reports for every candidate k.
DIMENSIONS = {str(k): {"log_cons": 14, "log_vars": 14} for k in range(pc.K_RANGE[0],
                                                                       pc.K_RANGE[1] + 1)}
# A shrunken TUNE-1 schedule for the end-to-end tests (N = 3 candidates, 2 instances:
# 2N = 6 blocks x 6 = 36 children instead of 882). The stub bench reads the lists from the
# run config, so shrinking the constants is enough; `test_poseidon_tuning_session` checks
# the exact full-size arithmetic separately.
SMALL_CANDIDATES = (10, 7, 9)
SMALL_INSTANCES = (1, 2)


def git(repo, *args):
    subprocess.run(["git", *args], cwd=repo, check=True, stdout=subprocess.DEVNULL,
                   stderr=subprocess.DEVNULL)


def make_repo(root):
    """A committed mini repository with the tracked files the runner reads."""
    repo = os.path.join(root, "repo")
    os.makedirs(os.path.join(repo, "specs", "poseidon"))
    os.makedirs(os.path.join(repo, "tests", "data"))
    os.makedirs(os.path.join(repo, "src"))
    os.makedirs(os.path.join(repo, "benches"))
    with open(os.path.join(repo, "Cargo.toml"), "w") as f:
        f.write(CARGO_TOML)
    with open(os.path.join(repo, "Cargo.lock"), "w") as f:
        f.write(CARGO_LOCK)
    for name in ("timing-schema-v2.json", "tuning-protocol-v2.json",
                 "comparison-schema-v2.json"):
        shutil.copyfile(os.path.join(REAL_REPO, "specs", "poseidon", name),
                        os.path.join(repo, "specs", "poseidon", name))
    shutil.copyfile(os.path.join(REAL_REPO, "tests", "data", "tune-corpus-v1.json"),
                    os.path.join(repo, "tests", "data", "tune-corpus-v1.json"))
    pc.write_canonical_json(os.path.join(repo, "specs", "poseidon",
                                         "security-accounting-v1.json"), SECURITY_FIXTURE)
    with open(os.path.join(repo, "benches", "poseidon_modp.rs"), "w") as f:
        f.write("fn main() {}\n")
    with open(os.path.join(repo, "src", "lib.rs"), "w") as f:
        f.write("#[rustfmt::skip]\npub mod poseidon_tuned_defaults;\n")
    pc.write_bytes(os.path.join(repo, GENERATED_MODULE), apply_tuning.render(None))
    git(repo, "init", "-q")
    git(repo, "config", "user.email", "test@example.invalid")
    git(repo, "config", "user.name", "test")
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", "fixture")
    return repo


def metadata_for(repo, **overrides):
    ids = {}
    for name in pc.SPEC_ORDER:
        _, sha = pc.load_spec(repo, name)
        ids[pc.SPEC_FILES[name][1]] = sha
    with open(os.path.join(repo, pc.COMPARISON_SCHEMA_PATH), "rb") as f:
        ids["comparison_schema_id"] = pc.sha256_hex(f.read())
    md = {"transcript_domain_separator": pc.TRANSCRIPT_ID,
          "protocol_wire_id": pc.PROTOCOL_WIRE_ID,
          "prime_sampler_id": pc.PRIME_SAMPLER_ID,
          "prime_sampler_caps": dict(pc.PRIME_SAMPLER_CAPS),
          "common_lift_binding_id": None,
          "benchmark_coins_id": pc.BENCHMARK_COINS_ID,
          "kat_fixture_sha256": pc.KAT_FIXTURE_SHA256,
          "criterion_version": "0.7.0", "panic_strategy": "unwind",
          "debug_assertions": False, "overflow_checks": False, "argv_forms_version": 2,
          "variants": list(pc.VARIANTS),
          "primary_groups": list(pc.PRIMARY_GROUPS),
          "diagnostic_groups": list(pc.DIAGNOSTIC_GROUPS),
          "tuning_epoch_id": None, "tuning_group_set": None, "tuned_defaults": [],
          "check_mode": "not_applicable",
          "dimensions_by_k": {k: dict(v) for k, v in DIMENSIONS.items()}}
    md.update(ids)
    md.update(overrides)
    return md


def write_metadata(root, repo, name="metadata.json", **overrides):
    path = os.path.join(root, name)
    with open(path, "w") as f:
        json.dump(metadata_for(repo, **overrides), f)
        f.write("\n")
    return path


def tuned_metadata(root, repo, bundle_path, name="metadata.json", **overrides):
    """Metadata of a bench compiled with the generated defaults of `bundle_path`."""
    with open(bundle_path, "rb") as f:
        data = f.read()
    bundle = pc.load_canonical_json(data)
    defaults = [{"backend": g["backend"], "k": g["selected"], "tuning_id": g["tuning_id"]}
                for g in bundle["groups"]]
    return write_metadata(root, repo, name=name, tuning_epoch_id=pc.sha256_hex(data),
                          tuning_group_set=bundle["group_set"], tuned_defaults=defaults,
                          **overrides)


def runner_env(**knobs):
    """The runner's environment: only mode knobs plus HOME/PATH (no test hooks)."""
    env = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"),
           "HOME": os.environ.get("HOME", "/")}
    for key, value in knobs.items():
        env[key] = str(value)
    return env


def install_stub(testcase, metadata_path, **settings):
    """Inject the stub build environment into the runner for one test."""
    previous = runner.be
    runner.be = sbe
    saved = dict(sbe.STUB_SETTINGS)
    for key in sbe.STUB_SETTINGS:
        sbe.STUB_SETTINGS[key] = None
    sbe.STUB_SETTINGS["metadata_json"] = metadata_path
    sbe.STUB_SETTINGS.update(settings)
    sbe.CREATED_TARGETS.clear()

    def restore():
        runner.be = previous
        sbe.STUB_SETTINGS.clear()
        sbe.STUB_SETTINGS.update(saved)
    testcase.addCleanup(restore)
    return sbe


def shrink_sweep(testcase, candidates=SMALL_CANDIDATES, instances=SMALL_INSTANCES):
    """Shrink the TUNE-1 candidate/instance lists for one test (restored on cleanup)."""
    saved = (pc.CANDIDATES, pc.K_ORDER, pc.SIMPLICITY_ORDER, pc.TUNING_INSTANCES)
    pc.CANDIDATES = pc.K_ORDER = tuple(candidates)
    pc.SIMPLICITY_ORDER = tuple(sorted(candidates))
    pc.TUNING_INSTANCES = tuple(instances)

    def restore():
        pc.CANDIDATES, pc.K_ORDER, pc.SIMPLICITY_ORDER, pc.TUNING_INSTANCES = saved
    testcase.addCleanup(restore)


def bytecode_snapshot():
    found = set()
    for dirpath, dirnames, filenames in os.walk(REAL_REPO):
        dirnames[:] = [d for d in dirnames if d not in (".git", "target")]
        if os.path.basename(dirpath) == "__pycache__":
            found.add(dirpath)
        for name in filenames:
            if name.endswith((".pyc", ".pyo")):
                found.add(os.path.join(dirpath, name))
    return found


def guard_bytecode(testcase):
    """Every test runs under `python3 -B` and creates no bytecode below the checkout."""
    testcase.assertTrue(sys.flags.dont_write_bytecode,
                        "run the suite with `python3 -B` (PYTHONDONTWRITEBYTECODE=1)")
    before = bytecode_snapshot()
    testcase.addCleanup(lambda: testcase.assertEqual(bytecode_snapshot() - before, set(),
                                                     "bytecode was written below the repo"))


def read_json(path):
    with open(path, "rb") as f:
        return json.loads(f.read().decode("utf-8"))
