#!/usr/bin/env python3
"""Render the tracked generated defaults module from a tuning bundle (plan v10, section 9;
limber contract section 6).

    apply_poseidon_tuning.py --bundle BUNDLE [--repo DIR] [--check]
    apply_poseidon_tuning.py --initial [--repo DIR] [--check]

This is the only writer of `src/poseidon_tuned_defaults.rs`. The module is rendered
deterministically from the bundle's group order (`hyrax`, `brakedown`), selected `k` values
and `tuning_id`s; `--check` compares the rendering with the tracked bytes instead of writing
(exit 3 on a difference). `--initial` renders the pre-epoch module (no tuned defaults: every
backend uses the persisted v9 default `k = 9`), which the tracked file must equal before the
first epoch. The runner's `normal prepare` renders the module from the bundle it copies and
requires the rendering to equal the tracked module (`generated_defaults_reproduced`); the
Zinc orchestrator may also pass its own rendering with `--rendered-defaults`.

The rendered module has no `#![rustfmt::skip]` (unstable inside a file); the includer adds
`#[rustfmt::skip]` on the `mod` item.
"""
from __future__ import annotations

import argparse
import os
import sys

try:
    from scripts import poseidon_common as pc
except ImportError:  # executed as a plain file
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import poseidon_common as pc  # noqa: E402

MODULE_PATH = "src/poseidon_tuned_defaults.rs"
GROUP_SET = "limber-both"
V9_DEFAULT_K = 9


def rust_str(value: str) -> str:
    if any(c in value for c in '"\\\n') or not value.isascii():
        raise pc.RunnerError("link", "BundleInvalid", "unrenderable string %r" % value)
    return '"%s"' % value


def render(bundle) -> bytes:
    """The complete module text for `bundle` (`None` renders the pre-epoch module)."""
    if bundle is None:
        head = [
            "//! GENERATED by `scripts/apply_poseidon_tuning.py` from a tuning bundle.",
            "//! Do not edit by hand: a normal run checks these bytes against fresh script",
            "//! output for the bundle it copies.",
            "//!",
            "//! No tuning epoch has been persisted yet: every backend uses the persisted",
            "//! v9 default `k = %d`." % V9_DEFAULT_K,
            "",
        ]
        epoch = "None"
        group_set = "None"
        entries = []
    else:
        data = pc.canonical_json_bytes(bundle)
        epoch_id = pc.sha256_hex(data)
        head = [
            "//! GENERATED by `scripts/apply_poseidon_tuning.py` from `tuning-bundle.json`",
            "//! with tuning_epoch_id `%s`." % epoch_id,
            "//! Do not edit by hand: a normal run checks these bytes against fresh script",
            "//! output for the bundle it copies.",
            "",
        ]
        epoch = "Some(%s)" % rust_str(epoch_id)
        group_set = "Some(%s)" % rust_str(str(bundle["group_set"]))
        entries = []
        seen = set()
        for g in bundle["groups"]:
            backend, k = g.get("backend"), g.get("selected")
            if backend not in pc.BACKENDS or backend in seen or not isinstance(k, int) or \
                    isinstance(k, bool) or not pc.K_RANGE[0] <= k <= pc.K_RANGE[1] or \
                    not pc.is_hex64(g.get("tuning_id")):
                raise pc.RunnerError("link", "BundleInvalid", "unrenderable group %r" % (g,))
            seen.add(backend)
            entries.append("  (%s, %d, %s)," % (rust_str(backend), k, rust_str(g["tuning_id"])))
    body = head + [
        "/// Exact-byte SHA-256 of the `tuning-bundle.json` these defaults were",
        "/// rendered from; `None` before the first epoch.",
        "pub const TUNING_EPOCH_ID: Option<&str> = %s;" % epoch,
        "",
        "/// Group set of the bundle (`\"%s\"`); `None` before the first epoch." % GROUP_SET,
        "pub const TUNING_GROUP_SET: Option<&str> = %s;" % group_set,
        "",
        "/// Selected `k` per backend together with the group-local `tuning_id`, in",
        "/// bundle group order (`hyrax`, `brakedown`). Empty before the first epoch:",
        "/// the bench then uses the persisted v9 default `k = %d` for every backend." %
        V9_DEFAULT_K,
    ]
    if entries:
        body.append("pub const TUNED_DEFAULTS: &[(&str, usize, &str)] = &[")
        body.extend(entries)
        body.append("];")
    else:
        body.append("pub const TUNED_DEFAULTS: &[(&str, usize, &str)] = &[];")
    text = "\n".join(body) + "\n"
    if len("pub const TUNING_EPOCH_ID: Option<&str> = %s;" % epoch) > 100:
        # rustfmt (max_width = 100, tab_spaces = 2) wraps a long constant initializer.
        text = text.replace(
            "pub const TUNING_EPOCH_ID: Option<&str> = %s;" % epoch,
            "pub const TUNING_EPOCH_ID: Option<&str> =\n  %s;" % epoch)
    return text.encode("ascii")


def load_bundle(path: str) -> dict:
    if not os.path.isfile(path):
        raise pc.RunnerError("cli", "UsageError", "--bundle %s is not a file" % path)
    with open(path, "rb") as f:
        data = f.read()
    obj = pc.load_canonical_json(data, "tuning-bundle.json")
    if not isinstance(obj, dict) or obj.get("generated_module_path") != MODULE_PATH or \
            not isinstance(obj.get("groups"), list):
        raise pc.RunnerError("link", "BundleInvalid", "bundle is not a defaults bundle for %s" %
                             MODULE_PATH)
    return obj


def main(argv=None, env=None) -> int:
    parser = argparse.ArgumentParser(prog="apply_poseidon_tuning.py",
                                     description=__doc__.split("\n")[0])
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument("--bundle")
    src.add_argument("--initial", action="store_true")
    parser.add_argument("--repo", help="repository root (default: this checkout)")
    parser.add_argument("--check", action="store_true",
                        help="compare with the tracked module instead of writing")
    parser.add_argument("--render-to", help="also write the rendering to this path")
    args = parser.parse_args(argv)
    env = os.environ if env is None else env
    try:
        repo = args.repo or pc.repo_root(env)
        rendered = render(None if args.initial else load_bundle(args.bundle))
        target = os.path.join(repo, MODULE_PATH)
        if args.render_to:
            pc.write_bytes(args.render_to, rendered)
        if args.check:
            try:
                with open(target, "rb") as f:
                    tracked = f.read()
            except OSError:
                tracked = None
            if tracked != rendered:
                pc.eprint("apply_poseidon_tuning: %s differs from the rendering" % target)
                return 3
            print("apply_poseidon_tuning: %s matches" % MODULE_PATH)
            return 0
        pc.write_bytes(target, rendered)
        print("apply_poseidon_tuning: wrote %s" % MODULE_PATH)
        return 0
    except pc.RunnerError as exc:
        pc.eprint("apply_poseidon_tuning: error %s" % exc)
        return exc.exit_code


if __name__ == "__main__":
    sys.exit(main())
