//! GENERATED by `scripts/apply_poseidon_tuning.py` from `tuning-bundle.json`
//! with tuning_epoch_id `7b704756a9f52ce796beb937fe0d5b2c9b4697d3a2ce80563335ac3d3bab0b6b`.
//! Do not edit by hand: a normal run checks these bytes against fresh script
//! output for the bundle it copies.

/// Exact-byte SHA-256 of the `tuning-bundle.json` these defaults were
/// rendered from; `None` before the first epoch.
pub const TUNING_EPOCH_ID: Option<&str> =
  Some("7b704756a9f52ce796beb937fe0d5b2c9b4697d3a2ce80563335ac3d3bab0b6b");

/// Group set of the bundle (`"limber-both"`); `None` before the first epoch.
pub const TUNING_GROUP_SET: Option<&str> = Some("limber-both");

/// Selected `k` per backend together with the group-local `tuning_id`, in
/// bundle group order (`hyrax`, `brakedown`). Empty before the first epoch:
/// the bench then uses the persisted v9 default `k = 9` for every backend.
pub const TUNED_DEFAULTS: &[(&str, usize, &str)] = &[
  ("hyrax", 9, "2abacde0de69ed2cbb2faae30bbe989ef733cf0024d036b9d14760ca8ff870ce"),
  ("brakedown", 9, "8becea8af4bc720feb2404db217245353d920179f14cf008d76de3654a1a30c1"),
];
