//! GENERATED by `scripts/apply_poseidon_tuning.py` from `tuning-bundle.json`
//! with tuning_epoch_id `9c15cbd916fe5995d96f26cc33f3033ea8eb7fd95198f441fe71223365b882f2`.
//! Do not edit by hand: a normal run checks these bytes against fresh script
//! output for the bundle it copies.

/// Exact-byte SHA-256 of the `tuning-bundle.json` these defaults were
/// rendered from; `None` before the first epoch.
pub const TUNING_EPOCH_ID: Option<&str> =
  Some("9c15cbd916fe5995d96f26cc33f3033ea8eb7fd95198f441fe71223365b882f2");

/// Group set of the bundle (`"limber-both"`); `None` before the first epoch.
pub const TUNING_GROUP_SET: Option<&str> = Some("limber-both");

/// Selected `k` per backend together with the group-local `tuning_id`, in
/// bundle group order (`hyrax`, `brakedown`). Empty before the first epoch:
/// the bench then uses the persisted v9 default `k = 9` for every backend.
pub const TUNED_DEFAULTS: &[(&str, usize, &str)] = &[
  ("hyrax", 9, "5bbed997bbe159348320ce48383156fe31491b7bf78d2abc2cec711a5b6af728"),
  ("brakedown", 9, "d6e540a5ea40efd32f001d9f751dc35befaf445ffa69c330aa5212cce3ffdce0"),
];
