//! GENERATED by `scripts/apply_poseidon_tuning.py` from a tuning bundle.
//! Do not edit by hand: a normal run checks these bytes against fresh script
//! output for the bundle it copies.
//!
//! No tuning epoch has been persisted yet: every backend uses the persisted
//! v9 default `k = 9`.

/// Exact-byte SHA-256 of the `tuning-bundle.json` these defaults were
/// rendered from; `None` before the first epoch.
pub const TUNING_EPOCH_ID: Option<&str> = None;

/// Group set of the bundle (`"limber-both"`); `None` before the first epoch.
pub const TUNING_GROUP_SET: Option<&str> = None;

/// Selected `k` per backend together with the group-local `tuning_id`, in
/// bundle group order (`hyrax`, `brakedown`). Empty before the first epoch:
/// the bench then uses the persisted v9 default `k = 9` for every backend.
pub const TUNED_DEFAULTS: &[(&str, usize, &str)] = &[];
